/** DO NOT MODIFY THIS FILE, ITS IS AUTOMATICALLY GENERATED ON EACH BUILD! **/

// Version numbers
#define BUILD_MAJOR_VERSION 0
#define BUILD_MINOR_VERSION 0
#define BUILD_PATCH_VERSION 0

// Build
#define BUILD_BUILD_NUMBER 179
#define BUILD_BUILD_DATE "Friday, 12 February 2021"
#define BUILD_BUILD_TIME "11:46:29"

// Git
#define BUILD_GIT_HASH "1bb5cde"
