/** DO NOT MODIFY THIS FILE, ITS IS AUTOMATICALLY GENERATED ON EACH BUILD! **/

// Version numbers
#define BUILD_MAJOR_VERSION 0
#define BUILD_MINOR_VERSION 0
#define BUILD_PATCH_VERSION 0

// Build
#define BUILD_BUILD_NUMBER 204
#define BUILD_BUILD_DATE "Sunday, 14 February 2021"
#define BUILD_BUILD_TIME "23:05:56"

// Git
#define BUILD_GIT_HASH "1aabcdc"
